install.packages("readr")
install.packages(“shiny”)
install.packages(“xlsx”)
install.packages(“rJava”)
install.packages(“xlsxjars”)
install.packages(“reshape2”)
install.packages(“ggplot2”)
install.packages(“g2sd”)
